# Generated by Django 5.0 on 2023-12-05 23:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="chat_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
