# Generated by Django 5.0 on 2026-07-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_alter_message_options_message_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('dark', 'Dark')], max_length=5, null=True),
        ),
    ]
